# FOLDER: ./experiments
SEED_VALUE: 1234
TRAIN:
  SPLIT: 'train'
  NUM_WORKERS: 2 # Number of workers
  BATCH_SIZE: 4 # Size of batches
  START_EPOCH: 0 # Start epoch
  END_EPOCH: 2000 # End epoch
  RESUME: '' # Experiment path to be resumed training
  PRETRAINED_VAE: ''
  PRETRAINED: '' # Pretrained model path

  OPTIM:
    OPTIM.TYPE: 'AdamW' # Optimizer type
    OPTIM.LR: 1e-4 # Learning rate

  ABLATION:
    VAE_TYPE: 'actor' # vae ablation: actor or mcross
    VAE_ARCH: 'encoder_decoder' # mdiffusion vae architecture
    PE_TYPE: 'actor' # mdiffusion mld or actor
    DIFF_PE_TYPE: 'actor' # mdiffusion mld or actor
    SKIP_CONNECT: False # skip connection for denoiser va
    # use linear to expand mean and std rather expand token nums
    MLP_DIST: False
    IS_DIST: False # Mcross distribution kl
    PREDICT_EPSILON: True # noise or motion

LOSS:
  LAMBDA_LATENT: 1e-5 # Lambda for latent losses
  LAMBDA_KL: 1e-5 # Lambda for kl losses
  LAMBDA_REC: 1.0 # Lambda for reconstruction losses
  LAMBDA_JOINT: 1.0 # Lambda for joint losses
  LAMBDA_GEN: 1.0 # Lambda for text-motion generation losses
  LAMBDA_CROSS: 1.0 # Lambda for cross-reconstruction losses
  LAMBDA_CYCLE: 1.0 # Lambda for cycle losses
  LAMBDA_PRIOR: 0.0
  DIST_SYNC_ON_STEP: True
METRIC:
  FORCE_IN_METER: True
  DIST_SYNC_ON_STEP: True
