hydra:
  run:
    dir: .
  output_subdir: null

mode: 'extract' # 'npy'
folder: ???
files: -1
jointstype: 'vertices'
walk: true
savedir: null
mean: false
fact: 1
number_of_samples: 1
ckpt_name: last # or a number
last_ckpt_path: ${get_last_checkpoint:${folder},${ckpt_name}}
temos_path: /is/cluster/fast/nathanasiou/data/motion-language/sinc-checkpoints/temos_score
path_to_gt: /is/cluster/fast/nathanasiou/data/sinc_supmat_gt
only_score: false
# submission | supmat | 'all'--> pairs + single (seg/seq) | pairs | single
set: pairs 

# naive == gpt | concat | null
naive: '' # for temos-indep compositions on rotations space

logger_level: INFO

defaults:
  - /path@path
  - _self_