
# Oracle experiment
# /is/cluster/work/nathanasiou/experiments/temos-original/samples
hydra:
  run:
    dir: .
  output_subdir: null

folder: ???
split: val

skip: false

mean: false
number_of_samples: 1
fact: 1

ckpt_name: last

# submission | supmat | 'all'--> pairs + single (seg/seq) | pairs | single
set: pairs 

# naive == gpt | concat | null
naive: null # for temos-indep compositions on rotations space

# smplh == positions == joints | vertices | rots --> rotations
jointstype: 'smplh' # smplh /

logger_level: INFO

defaults:
  - data: null
  - /path@path
  - /transforms/rots2joints/smplh@rots2joints
  - sampler: all_conseq
  - override hydra/job_logging: console
  - override hydra/hydra_logging: console
  - _self_

data:
  mode: 'inference'

machine:
  smpl_batch_size: 256
