name: multi_actor_encoder
_target_: sinc.model.motionencoder.MultiActorAgnosticEncoder

latent_dim: ${model.latent_dim}
vae: ${model.vae}

ff_size: ${model.ff_size}
num_layers: ${model.num_layers}
num_head: ${model.num_head}
droupout: ${model.droupout}
activation: ${model.activation}
